// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj57BZWsP6Y2zgH6zjJ1FGoeosTb0spTI',
    appId: '1:688771040502:web:e9b310419838fbad8458d7',
    messagingSenderId: '688771040502',
    projectId: 'personal-expense-tracker-30d82',
    authDomain: 'personal-expense-tracker-30d82.firebaseapp.com',
    storageBucket: 'personal-expense-tracker-30d82.appspot.com',
    measurementId: 'G-3CWC354R76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsXFL8mgQfkjjlsmH9wkcAIwGdQOU6tMY',
    appId: '1:688771040502:android:73a0cb98517fdff28458d7',
    messagingSenderId: '688771040502',
    projectId: 'personal-expense-tracker-30d82',
    storageBucket: 'personal-expense-tracker-30d82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXycj_3_wwQR_rCZduMbBEQn6MZYuO-io',
    appId: '1:688771040502:ios:4e3e273f839890738458d7',
    messagingSenderId: '688771040502',
    projectId: 'personal-expense-tracker-30d82',
    storageBucket: 'personal-expense-tracker-30d82.appspot.com',
    iosBundleId: 'com.example.personalExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXycj_3_wwQR_rCZduMbBEQn6MZYuO-io',
    appId: '1:688771040502:ios:4e3e273f839890738458d7',
    messagingSenderId: '688771040502',
    projectId: 'personal-expense-tracker-30d82',
    storageBucket: 'personal-expense-tracker-30d82.appspot.com',
    iosBundleId: 'com.example.personalExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj57BZWsP6Y2zgH6zjJ1FGoeosTb0spTI',
    appId: '1:688771040502:web:a7eb2baa2361b9748458d7',
    messagingSenderId: '688771040502',
    projectId: 'personal-expense-tracker-30d82',
    authDomain: 'personal-expense-tracker-30d82.firebaseapp.com',
    storageBucket: 'personal-expense-tracker-30d82.appspot.com',
    measurementId: 'G-FMECJ4104P',
  );
}
